### ISSUE TITLE
Add Event in Take function

### ISSUE THREAD

**Issue by adamskrodzki** [ajna-finance/ajna-core#425]
https://github.com/ajna-finance/contracts/blob/develop/src/erc20/ERC20Pool.sol

has function
`function take(
        address        borrowerAddress_,
        uint256        collateral_,
        address        callee_,
        bytes calldata data_
    )`

without event,
 please ensure you have all events required to track both collateral and debt amount of every borrow position

**Comment by grandizzy** [comment]
that's actually done in external Auctions library here: https://github.com/ajna-finance/contracts/blob/develop/src/libraries/external/Auctions.sol#L546
as a pattern we're emitting common ERC20 / ERc721 events in external libraries or Pool base contract, for events that are different (like add / remove collateral) they're emitted in Pool implementations
will check all the code for consistency, (e.g. moving `Settle` event in external library)

**Comment by grandizzy** [comment]
properly emmitting events was addressed with https://github.com/ajna-finance/contracts/pull/443
