### ISSUE TITLE
Upper and lower boundaries of deposit size are not defined

### ISSUE THREAD

**Issue by EdNoepel** [ajna-finance/ajna-core#439]
- When depositing large amounts at high prices (low indexes), balances can overflow a `uint256` causing a revert.  For buckets with quote token deposited, interest accumulation makes this problematic.
- When depositing small amounts at low prices (high indexes), there is insufficient precision to for LP accounting to function as intended.

For collateral deposited into a bucket, the bucket price becomes a factor in the equation to determine bounds.
Token scale is another factor in this equation.

**Comment by EdNoepel** [comment]
In today's standup, it was recommended we simply document the _upper_ limit as a known and accepted limitation.

**Comment by ith-harvey** [comment]
@EdNoepel are we OK to close this issue? If so, please close it.
