### ISSUE TITLE
Store single auction refrence price 

### ISSUE THREAD

**Issue by grandizzy** [ajna-finance/ajna-core#537]
- right now we store both `liquidation_.kickMomp` and `liquidation_.neutralPrice`
- when auction price is calculated the greatest of two is used as `referencePrice`
- optimize and store the `referencePrice` at time of kick (as the max of momp and neutralPrice) and use it when auction price is calculated

**Comment by grandizzy** [comment]
`neutralPrice` it is usd in BPF calculation so this could be not an issue

**Comment by grandizzy** [comment]
confirmed neutral price is needed for calculating BPF. the only improvement we could do is to store referencePrice instead MOMP

**Comment by ith-harvey** [comment]
This is a gas optimization not a bug. PR here resolves the issue -> https://github.com/ajna-finance/contracts/pull/554

Going to bring up in standup tomorrow Feb 22nd.

**Comment by grandizzy** [comment]
@ith-harvey not sure that's still a change to be done in this stage?
