### ISSUE TITLE
duplicate inflator multiplication in pool HTP calculation

### ISSUE THREAD

**Issue by ith-harvey** [ajna-finance/ajna-core#686]
## Issue
We multiply by the inflator twice in our htp calculation inside the `infoUtils.poolPricesInfo()` method and the `infoUtils.htp()` method. 

* Once when we retrieve maxThresholdPrice from `pools.loansInfo()` -> https://github.com/ajna-finance/contracts/blob/65bcd8ea791f4c70452768e4ebe15efd8f1430b6/src/base/Pool.sol#L889
* and a second time inside the `poolPricesInfo()` method itself -> https://github.com/ajna-finance/contracts/blob/65bcd8ea791f4c70452768e4ebe15efd8f1430b6/src/PoolInfoUtils.sol#L156
* There is also that second multiplication in the `htp()` method -> https://github.com/ajna-finance/contracts/blob/65bcd8ea791f4c70452768e4ebe15efd8f1430b6/src/PoolInfoUtils.sol#L319

## Possible Solution
* Remove the inflator multiplications in the outer methods and only perform it once inside `pools.loansInfo()` when we return `maxThresholdPrice`

**Comment by grandizzy** [comment]
fixed in https://github.com/ajna-finance/contracts/pull/685
