### ISSUE TITLE
Properly handle collaterlized loans in `Pool.settle`

### ISSUE THREAD

**Issue by grandizzy** [ajna-finance/ajna-core#694]
- when calling `settle` we should first check if loan is collateralized (this could happen if LUP moves for example) and if so just remove from queue and add it in loan heap
- at this moment settle assumes loan is undercollateralized and swaps collateral in HPB / settle with reserves / forgive debt until debt in loan goes to 0, then removes loan from queue

**Comment by EdNoepel** [comment]
Believe this was fixed in RC4; can we close?

**Comment by grandizzy** [comment]
nope, the discussion re this fall off the radar
